name = "TriangularSolve"
uuid = "d5829a12-d9aa-46ab-831f-fb7c9ab06edf"
authors = ["chriselrod <elrodc@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CloseOpenIntervals = "fb6a15b2-703c-40df-9091-08a04967cfa9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
CloseOpenIntervals = "0.1"
VectorizationBase = "0.20"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
